Feature/footer background
Kyle-Roman/parcel-project-group-9 pull request #4
Opened 2021-04-23 16:00 UTC by NikaProkopeva

2021-04-23 16:01 UTC, NikaProkopeva commented
не уверена на счет цвета в футере. отличается от переменных.

2021-04-23 16:38 UTC, Kyle-Roman requested changes

2021-04-23 16:38 UTC, Kyle-Roman commented on src/sass/layout/_footer.scss
> +  background-color: #fff5f6;
Цвет правильный. В переменных он значится --background-color-main: #fff5f6;

2021-04-23 16:38 UTC, Kyle-Roman commented on src/partials/footer.html
> +<p class="description">homemade ice cream made <span>with passion</span></p>
По заголовку. Я сделал в  sass/components/section-title. Там задумывал описать классы для всех заголовков на странице они одинаковые. Задумывалось как <h3 class "section-title">With passion<h3> и <p class "section-suptitle">Homemade ice cream with<p>.  И все заголовки опишем этими классами

2021-04-23 21:41 UTC, NikaProkopeva commented on src/partials/footer.html
> +<p class="description">homemade ice cream made <span>with passion</span></p>
поправила заголовки, создала компонент subtitle, подключила к main

2021-04-24 04:35 UTC, Kyle-Roman approved these changes

2021-04-24 04:35 UTC, merged